#
# This file is applied automatically by docker-compose
# see: https://docs.docker.com/compose/extends/
#
# This docker-compose is used to run everything in production setup on .localhost domain
#
# portainer:
#   # See README.md in portainer dir for more info on working with portainer
#   container_name: portainer.moonspeak.localhost
#   volumes:
#     - /var/run/docker.sock:/var/run/docker.sock
#     # use anon volume during local dev
#     - /data
#   build:
#     context: ./portainer
#
# Important: you might need to define moonspeak.localhost in /etc/hosts 
#
# port definitions for services are for debug/development,
# except the gateway service which is expected to be exposed to the internet
#
# For pdb debug add to service definition:
#   stdin_open: true  # docker run -i
#   tty: true         # docker run -t
# and run "docker attach CONTAINER_NAME"
#
version: "3"

volumes:
  # volume for demouser1
  userdata:
    name: demouser1_userdata

services:
  #===================================
  gateway:
    container_name: moonspeak.localhost
    build:
      context: ./gateway
    ports:
      - "80:8443"   # listens on 8433 to redirect to https port 443
      - "443:443"
    command: nginx-debug -g "daemon off; error_log stderr debug;"

  router:
    container_name: router.moonspeak.localhost
    build:
      context: ./router
    environment:
      MOONSPEAK_DOMAIN: "moonspeak.localhost"
      # dev mode relaxes a number of restrictions (e.g. must have access to gateway's unix socket)
      # also enables self-handling of routes instead of gateway which can be confusing!
      # so do NOT enable this if gateway is enabled, only enable devmode without gateway
      MOONSPEAK_DEV_MODE: ""
      RUST_LOG: "router=debug"

  #===================================
  manager:
    container_name: manager.moonspeak.localhost
    build:
      context: ./manager
    environment:
      TAG: "latest"
      MOONSPEAK_TLD: "localhost"
      MOONSPEAK_DEVMODE: ""

      # settings for container spin down (container stop & rm)
      MOONSPEAK_SECONDS_BEFORE_IDLE_SPINDOWN: 70
      # must check at least once a minute
      MOONSPEAK_MAX_INTERVAL_DURATION_SECONDS: 30
      # never check more often than once every 10 seconds
      MOONSPEAK_MIN_INTERVAL_DURATION_SECONDS: 10

      # manager will never spin down containers for this user, even after period of inactivity
      MOONSPEAK_IGNORED_DEMO_USER: "demouser1"

      # set debug to on
      PYTHON_ON_WHALES_DEBUG: "1"
      LOGLEVEL: "DEBUG"
    ports:
      - "8001:80"

  # loki, promtail and grafana stack for logs
  # see: https://mpolinowski.github.io/docs/DevOps/Provisioning/2021-04-07--loki-prometheus-grafana/2021-04-07/
  promtail:
    container_name: promtail.moonspeak.localhost
    build:
      context: ./promtail
    environment:
      MOONSPEAK_LOKI_URL: "http://loki.moonspeak.localhost:3100"
      PROMTAIL_LOG_LEVEL: "error"

  loki:
    container_name: loki.moonspeak.localhost
    image: grafana/loki:2.8.2
    command: -config.file=/etc/loki/local-config.yaml -log.level=error
    networks:
      - moonspeaknet

  grafana:
    container_name: grafana.moonspeak.localhost
    image: "temachpool/moonspeak-grafana:${TAG:-latest}"
    build:
      context: ./grafana
    environment:
      MOONSPEAK_LOKI_URL: "http://loki.moonspeak.localhost:3100"
      GF_SERVER_DOMAIN: "grafana.moonspeak.localhost"
      GF_SERVER_ROOT_URL: ""
      GF_SERVER_SERVE_FROM_SUB_PATH: ""
      GF_SERVER_PROTOCOL: "http"
      GF_LOG_LEVEL: "error"
      # allow anonymous user login, see: https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/#anonymous-authentication
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      # or login with moonspeak:moonspeak
      # GF_SECURITY_ADMIN_USER: "moonspeak"
      # GF_SECURITY_ADMIN_PASSWORD: "moonspeak"
    networks:
      - moonspeaknet
    ports:
      - "3000:3000"

  landing:
    container_name: landing.moonspeak.localhost
    build:
      context: ./landing
    ports:
      - "8002:80"
    command: nginx-debug -g "daemon off; error_log stderr debug;"

  synonyms:
    container_name: synonyms.moonspeak.localhost
    build:
      context: ./synonyms
    ports:
      - "8043:80"

  suggestions:
    container_name: suggestions.moonspeak.localhost
    build:
      context: ./suggestions
    ports:
      - "8042:80"

  frequency:
    container_name: frequency.moonspeak.localhost
    build:
      context: ./frequency
    ports:
      - "8005:80"

  #==================================
  # this is the demo user for development,  graph address is the user's unique access url
  workelements:
    image: "temachpool/moonspeak-workelements:${TAG:-latest}"
    container_name: u-demouser1-s-workelements.moonspeak.localhost
    build:
      context: ./workelements
    volumes:
      - userdata:/opt/moonspeak/workelements/userdata
    networks:
      - moonspeaknet
    environment:
      LOGLEVEL: "INFO"
      MOONSPEAK_DEVMODE: ""
      MOONSPEAK_HOST: "0.0.0.0"
      MOONSPEAK_PORT: "80"
    ports:
      - "8040:80"

  graph:
    image: "temachpool/moonspeak-graph:${TAG:-latest}"
    container_name: u-demouser1-s-graph.moonspeak.localhost
    # prioritise graph startup time over unlikely race condition, so drop depends_on
    # depends_on:
    #   - workelements
    build:
      context: ./graph
    volumes:
      - userdata:/opt/moonspeak/graph/userdata
    networks:
      - moonspeaknet
    ports:
      - "8041:80"
    environment:
      LOGLEVEL: "INFO"
      MOONSPEAK_DEVMODE: ""
      MOONSPEAK_HOST: "0.0.0.0"
      MOONSPEAK_PORT: "80"
      # this xml sets default graph value
      MOONSPEAK_GRAPH_INITIAL_XML: >-
        <mxfile host="moonspeak.localhost" modified="2023-03-08T09:50:31.755Z" agent="5.0 (X11; Ubuntu)" etag="x1sPpmzUOXcRObYpYGWO" version="20.3.0" type="moonspeak">
          <diagram id="SKebBaCcsGTVzdhOYIFn" name="pageWithNumber">
            <mxGraphModel dx="3702" dy="1137" grid="1" gridSize="10" guides="1" tooltips="0" connect="1" arrows="0" fold="1" page="0" pageScale="1" pageWidth="850" pageHeight="1100" math="0" shadow="0">
              <root>
                <mxCell id="0" />
                <mxCell id="1" style="locked=1;" parent="0" />
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="workelements" src="/router/route/u-demouser1-s-workelements/" style="width: 680px; height: 560px; border: medium none;" pointer-events="none" id="2">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="-210" y="-70" width="700" height="580" as="geometry" />
                  </mxCell>
                </iframe>
                <mxCell id="11" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;entryX=0.003;entryY=0.384;entryDx=0;entryDy=0;entryPerimeter=0;" parent="1" source="4" target="2" edge="1">
                  <mxGeometry relative="1" as="geometry" />
                </mxCell>
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="suggestions" src="/router/route/suggestions/" style="width: 380px; height: 290px; border: medium none;" pointer-events="none" id="4">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="-700" y="120" width="400" height="310" as="geometry" />
                  </mxCell>
                </iframe>
                <mxCell id="12" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;" parent="1" source="5" target="2" edge="1">
                  <mxGeometry relative="1" as="geometry" />
                </mxCell>
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="synonyms" src="/router/route/synonyms/" style="width: 474px; height: 424px; border: medium none;" pointer-events="none" id="5">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="560" width="490" height="440" as="geometry" />
                  </mxCell>
                </iframe>
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="frequency" src="/router/route/frequency/" style="width: 380px; height: 290px; border: medium none;" pointer-events="none" id="6">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="-700" y="-260" width="400" height="310" as="geometry" />
                  </mxCell>
                </iframe>
                <object label="freehand" id="JOpQ_ee-CrSYCSZTWhDq-18">
                  <mxCell style="" parent="0" />
                </object>
              </root>
            </mxGraphModel>
          </diagram>
        </mxfile>
