#
# This docker-compose runs production setup for .localhost domain
# It should be used as a template for other production domains
#
version: "3"

services:
  #===================================
  gateway:
    container_name: moonspeak.localhost
    restart: always
    # volumes:
    #   - "/etc/letsencrypt/live/moonspeak.ru/fullchain.pem:/etc/nginx/fullchain.pem:ro"
    #   - "/etc/letsencrypt/live/moonspeak.ru/privkey.pem:/etc/nginx/privkey.pem:ro"
    ports:
      - "80:8443"   # listens on 8433 to redirect to https port 443
      - "443:443"

  router:
    container_name: router.moonspeak.localhost
    restart: always
    environment:
      MOONSPEAK_DOMAIN: "moonspeak.localhost"

  #===================================
  manager:
    container_name: manager.moonspeak.localhost
    restart: always
    environment:
      TAG: "2023-02-19"
      MOONSPEAK_TLD: "localhost"
      # settings for container spin down (container stop & rm)
      MOONSPEAK_SECONDS_BEFORE_IDLE_SPINDOWN: 600

  # on prod run only promtail and send logs to grafana cloud dashboard
  promtail:
    container_name: promtail.moonspeak.localhost
    environment:
      MOONSPEAK_LOKI_URL: "${MOONSPEAK_LOKI_URL:?Set MOONSPEAK_LOKI_URL env var to stream logs to grafana cloud: https://grafana.com/orgs/moonspeakorg/hosted-logs}"
      PROMTAIL_LOG_LEVEL: "error"
    restart: always

  landing:
    container_name: landing.moonspeak.localhost
    restart: always

  synonyms:
    container_name: synonyms.moonspeak.localhost
    restart: always

  suggestions:
    container_name: suggestions.moonspeak.localhost
    restart: always
