#
# using env variables in compose file, see: https://docs.docker.com/compose/environment-variables/env-file/#parameter-expansion
#

version: "3"

services:
  workelements:
    # if devmode user count is 1, will give port mapping like "12000:80"
    ports:
      - "${MOONSPEAK_DEVMODE_COUNT:?You must set MOONSPEAK_DEVMODE_COUNT env var, e.g. MOONSPEAK_DEVMODE_COUNT=1}0002:80"
    environment:
      MOONSPEAK_PORT: "80"

  graph:
    # if devmode user count is 1, will give port mapping like "12000:80"
    ports:
      - "${MOONSPEAK_DEVMODE_COUNT}0001:80"
    environment:
      MOONSPEAK_PORT: "80"
      # this xml sets default graph value
      MOONSPEAK_GRAPH_INITIAL_XML: >-
        <mxfile host="moonspeak.localhost" modified="2023-03-08T09:50:31.755Z" agent="5.0 (X11; Ubuntu)" etag="x1sPpmzUOXcRObYpYGWO" version="20.3.0" type="moonspeak">
          <diagram id="SKebBaCcsGTVzdhOYIFn" name="pageWithNumber">
            <mxGraphModel dx="3702" dy="1137" grid="1" gridSize="10" guides="1" tooltips="0" connect="1" arrows="0" fold="1" page="0" pageScale="1" pageWidth="850" pageHeight="1100" math="0" shadow="0">
              <root>
                <mxCell id="0" />
                <mxCell id="1" style="locked=1;" parent="0" />
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="workelements" src="http://moonspeak.localhost:${MOONSPEAK_DEVMODE_COUNT}0002" style="width: 680px; height: 560px; border: medium none;" pointer-events="none" id="2">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="-210" y="-70" width="700" height="580" as="geometry" />
                  </mxCell>
                </iframe>
                <mxCell id="11" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;entryX=0.003;entryY=0.384;entryDx=0;entryDy=0;entryPerimeter=0;" parent="1" source="4" target="2" edge="1">
                  <mxGeometry relative="1" as="geometry" />
                </mxCell>
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="suggestions" src="http://moonspeak.localhost:8042" style="width: 380px; height: 290px; border: medium none;" pointer-events="none" id="4">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="-700" y="120" width="400" height="310" as="geometry" />
                  </mxCell>
                </iframe>
                <mxCell id="12" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;" parent="1" source="5" target="2" edge="1">
                  <mxGeometry relative="1" as="geometry" />
                </mxCell>
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="synonyms" src="http://moonspeak.localhost:8043" style="width: 474px; height: 424px; border: medium none;" pointer-events="none" id="5">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="560" width="490" height="440" as="geometry" />
                  </mxCell>
                </iframe>
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="frequency" src="http://moonspeak.localhost:8005" style="width: 380px; height: 290px; border: medium none;" pointer-events="none" id="6">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="-700" y="-260" width="400" height="310" as="geometry" />
                  </mxCell>
                </iframe>
                <object label="freehand" id="JOpQ_ee-CrSYCSZTWhDq-18">
                  <mxCell style="" parent="0" />
                </object>
              </root>
            </mxGraphModel>
          </diagram>
        </mxfile>
